name             'craft'
maintainer       'David Cannon'
maintainer_email 'david.cannon@creditcards.com'
license          'All rights reserved'
description      'Installs/Configures Craft cms'
long_description 'Installs/Configures Craft cms'
version          '0.0.1'

depends 'yum'
depends 'yum-remi'
depends 'php'
depends 'apache2'
depends 'mysql', '~> 6.1.2'
depends 'database', '~> 4.0.9'
depends 'mysql2_chef_gem', '~> 1.0.2'
depends 'mongodb', '~> 0.16.2'
depends 'subversion', '~> 1.3.1'
